

spring:
  application:
    name: microservicea
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8181/realms/prem_realm
          jwt-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

server:
  port: 8082

jwt:
  auth:
    converter:
      principle-attribute: preferred_username
      resource-id: microserviceA_clientId

